### ISSUE TITLE
Create Exercise for admin

### ISSUE THREAD

**Issue by demetrisperdikos** [Giansingh4710/cs490_exercise_app_backend#81]

**Comment by Julian-Hame** [comment]
Should be accessible via _http://localhost:1313/exercises/createExercise_

Here's an example on what input data might look like in JSON format:

{
  "name": "Pistol Squat",
  "muscleGroup": "Leg",
  "difficulty": "Intermediate",
  "equipment": "Dumbells",
  "type": "Compound",
  "metric": "Reps"
}

Edit: I updated the endpoint so that it no longer requires an exerciseID as input, so it should create one automatically.
