### ISSUE TITLE
Deactivate Exercise/Activate

### ISSUE THREAD

**Issue by demetrisperdikos** [Giansingh4710/cs490_exercise_app_backend#91]

**Comment by Julian-Hame** [comment]
Should be accessible via _/exercises/enableExercise_
Also, the delete exercise endpoint was changed to disable exercise, and can be accessed via _/exercises/disableExercise_. It should now be treated as a GET method rather than a DELETE method.

So to disable exercise with ID 70, you would visit:
[http://localhost:1313/exercises/disableExercise?exerciseID=70](http://localhost:1313/exercises/disableExercise?exerciseID=70)

And to enable exercise with ID 70, you would visit:
[http://localhost:1313/exercises/enableExercise?exerciseID=70](http://localhost:1313/exercises/enableExercise?exerciseID=70)
